'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FinalProject.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _450923602_1012591656986524_7740550422230138520_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("450923602_1012591656986524_7740550422230138520_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _450923602_1012591656986524_7740550422230138520_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("450923602_1012591656986524_7740550422230138520_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _485276670_532197599538322_4072634713528894327_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("485276670_532197599538322_4072634713528894327_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _485760242_680612651203557_3731515289601896556_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("485760242_680612651203557_3731515289601896556_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _486162027_1165767628120016_8680747603917700561_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("486162027_1165767628120016_8680747603917700561_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _486167724_674857904938361_2974895684361613516_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("486167724_674857904938361_2974895684361613516_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _486187339_1707915343403263_4027160361555394642_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("486187339_1707915343403263_4027160361555394642_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _486396800_1608882446492746_5113827602385221957_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("486396800_1608882446492746_5113827602385221957_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _486426255_2133720930407667_8028717441049883819_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("486426255_2133720930407667_8028717441049883819_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _486496613_1387992992335090_1476690870979347427_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("486496613_1387992992335090_1476690870979347427_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _487077387_969406941979670_7867420970671015424_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("487077387_969406941979670_7867420970671015424_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cappa_Kickz_shoe_shop_logo_with_clear_text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cappa Kickz shoe shop logo with clear text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property custom_nike_air_max_97_shoes_by_you() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("custom-nike-air-max-97-shoes-by-you", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property F6341_1485_right1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F6341_1485_right1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
